after_include: >
  using namespace NetCDF;

module NetCDF:
  enum Type: [String, Int8, Int16, Int32, Int64, SFloat, DFloat, UInt8, UInt16, UInt32, UInt64]

  def:
    self.version:

  class File:
    attr_reader: [path, mode]

    def:
      initialize | NetCDF::File.DEFAULT: [[const string &, path], [string, mode = (string)"r"]]
      open: [path, mode = (string)"r"]
      reopen: [mode = (string)"r"]
      close:
      reload:
      sync:
      null? | is_null:
      dims:
      vars:
      atts:
      create_dim: [name, size = (size_t)NC_UNLIMITED] # unlimited if size is 0
      create_var:
      write_att:
      set_fill:

  class Dim:
    def:
      name:
      name=      | rename:
      null?      | is_null:
      unlimited? | is_unlimited:
      size:

  class Att:
    attr_reader: [name]

    def:
      name= | rename:
      type  | type_name:
      null? | is_null:
      size:
      read:
      destroy:
      copy:
        - { void const: [const File & dst] }
        - { void const: [const Var & dst] }

  class Var:
    def:
      name:
      name= | rename:
      type  | type_name:
      null? | is_null:
      dims_count:
      dims:
      atts:
      shape:
      write_att:
      write: [values, starts = vector< size_t >(), counts = vector< size_t >(), strides = vector< ptrdiff_t >()]
      read:
      fill_value:
      fill_value= | set_fill_value:
      fill:
      set_fill:
      endian:
      set_endian:
      checksum:
      set_checksum:
      deflate:
      set_deflate:
      quantize:
      set_quantize:
      chunking:
      set_chunking:
      chunk_cache:
      set_chunk_cache:
