# docker compose down && docker volume rm $(docker volume ls -q) && docker compose up -d --force-recreate --build postgres-18
services:
  postgres-18:
    build: docker/postgres/18
    security_opt:
      - seccomp:unconfined
    ports:
      - "127.0.0.1:5438:5438"
    volumes:
      - postgres-18:/var/lib/postgresql
      - ./docker/postgres/18/files:/docker-entrypoint-initdb.d/files
      - ./docker/postgres/18/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    restart: always
    logging: &log
#      <<: *log
      options:
        max-size: "10m"
        max-file: "5"
    environment: &env
#    environment: *env
      - POSTGRES_PASSWORD=postgres
volumes:
  postgres-18: {}
