window.lru = require('tiny-lru').lru
window.Cookies = require('js-cookie')
require('@@lib/ext_coffee/core_ext/polyfills/custom_event')
require('@@lib/ext_coffee/core_ext/polyfills/performance_now')
require('@@lib/ext_coffee/core_ext/polyfills/replace_with')
require('@@lib/ext_coffee/core_ext/polyfills/request_animation_frame')
require('@@lib/ext_coffee/core_ext/polyfills/request_submit')
require('@@lib/ext_coffee/core_ext/env')
require('@@lib/ext_coffee/core_ext/logger')
require('@@lib/ext_coffee/core_ext/window')
require('@@lib/ext_coffee/core_ext/cookie')
require('@@lib/ext_coffee/core_ext/element')
require('@@lib/ext_coffee/core_ext/object')
require('@@lib/ext_coffee/core_ext/array')
require('@@lib/ext_coffee/core_ext/boolean')
require('@@lib/ext_coffee/core_ext/function')
require('@@lib/ext_coffee/core_ext/json')
require('@@lib/ext_coffee/core_ext/math')
require('@@lib/ext_coffee/core_ext/number')
require('@@lib/ext_coffee/core_ext/regexp')
require('@@lib/ext_coffee/core_ext/string')
require('@@lib/ext_coffee/core_ext/xhr')
require('@@vendor/rails-ujs/all')
require('@@lib/ext_coffee/core_ext/i18n')
require('@@lib/ext_coffee/core_ext/date')
require('@@lib/ext_coffee/core_ext/duration')
require('@@lib/ext_coffee/core_ext/rescue')
