sun.install "gdal-bin"
sun.install "libgdal-dev"

sun.install "python3-dev"
sun.install "python3-pyproj"
sun.install "python3-rasterio"
sun.install "python3-matplotlib"
sun.install "python3-numpy"
sun.install "python3-psycopg2"
sun.install "python3-netcdf4"
