#include <rice/rice.hpp>
#include <rice/stl.hpp>
#include "rice/conversions.hpp"
#include "ext_rice/core_ext/runtime_error.hpp"
#include "ext_rice/core_ext/finally.hpp"
#include "ext_rice/core_ext/c.hpp"
#include "ext_rice/core_ext/logger.hpp"
#include "ext_rice/core_ext/types.hpp"
#include "ext_rice/core_ext/bitset.hpp"
#include "ext_rice/core_ext/gtype.hpp"
