require 'ext_bootstrap'
require 'ext_capistrano'
# require 'ext_minitest'
require 'ext_pjax'
require 'ext_rails'
require 'ext_ruby'
require 'ext_vue'
require 'ext_webpacker'
# require 'ext_whenever'
# require 'mix_admin'
require 'mix_backup'
require 'mix_credential'
require 'mix_email'
# require 'mix_file'
require 'mix_geo'
require 'mix_global'
# require 'mix_log'
# require 'mix_page'
require 'mix_rescue'
require 'mix_search'
require 'mix_server'
require 'mix_setting'
require 'mix_sql'
require 'mix_task'
require 'mix_template'
# require 'mix_user'
require 'sunzistrano'
