require 'ext_coffee'
# require 'ext_minitest'
require 'ext_rails'
require 'ext_ruby'
require 'ext_css'
require 'ext_shakapacker'
# require 'ext_whenever'
# require 'mix_admin'
require 'mix_certificate'
require 'mix_file'
require 'mix_flash'
require 'mix_geo'
require 'mix_global'
require 'mix_job'
# require 'mix_page'
require 'mix_rpc'
require 'mix_search'
require 'mix_server'
require 'mix_setting'
require 'mix_task'
# require 'mix_user'
require 'sunzistrano'
