makefile:
  cflags: -std=c++23 -fjump-tables -Wno-format-overflow

libs:
  - stdc++_libbacktrace

include:
  - chrono
  - fstream
  - filesystem
  - source_location
  - stacktrace
  - unordered_set
  - unordered_map
  - numeric
  - valarray

module C:
  NIL: C::Nil
  NAN: C::NaN
  INF: C::Inf
