cling:
  - ext_rice/core_ext/c.hpp
  - ext_rice/core_ext/types.hpp
  - ext_rice/core_ext/bitset.hpp

makefile:
  cflags: -std=c++23 -fjump-tables -Wno-format-overflow

libs:
  - stdc++_libbacktrace
  - tbb

include:
  - chrono
  - fstream
  - filesystem
  - source_location
  - stacktrace
  - execution
  - atomic
  - stdfloat
  - numeric
  - ranges
  - optional
  - variant
  - queue
  - unordered_set
  - unordered_map
  - valarray

module C:
  DOUBLE_SAFE_INT64:
  FLOAT_SAFE_INT32:

class Bitset:
  def:
    initialize | ::Bitset.COPY:
      - { [[size_t, count]] }
      - { [[const Vbool &, bools]] }
    "[] | operator[]": { bool const: [size_t i] }
    "[]=": >
      [](Bitset & self, size_t i, bool value) -> bool {
        self[i] = value;
        return value;
      }
    first | front: { bool const: [] }
    last  | back:  { bool const: [] }
    size:
    to_s:
