before_initialize: >
  Numo::init_conversion();

makefile:
  cflags: -std=c++23 -fjump-tables -Wno-format-overflow

libs:
  - stdc++_libbacktrace

include:
  - chrono
  - fstream
  - filesystem
  - source_location
  - stacktrace
  - unordered_set
  - unordered_map

module C:
  NIL: C::Nil
  NAN: C::NaN
  INF: C::Inf

module Numo:
  enum Type | Numo::Type: [<%= compile_vars[:numo_types].join(', ') %>]
