before_initialize: >
  Numo::init_conversion();

makefile:
  cflags: -std=c++23 -Wno-format-overflow

libs:
  - stdc++_libbacktrace

include:
  - chrono
  - fstream
  - filesystem
  - source_location
  - stacktrace

module Numo:
  enum Type | Numo::Type: [<%= compile_vars[:numo_types].join(', ') %>]
