require 'minitest/mr_backend/action_controller/test_case'
require 'minitest/mr_backend/action_dispatch/integration_test'
require 'minitest/mr_backend/action_dispatch/system_test'
require 'minitest/mr_backend/action_view/template/error'
require 'minitest/mr_backend/javascript/test_case'
require 'minitest/ext_rake'
require 'minitest/ext_sql'
require 'minitest/mr_template'
