lock: 0.2.0
types:
gems:
  - ext_rice
  - mix_server

shared:
  authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILSLbcjZM3817COyl7ErGhVU0l0LtO8P6W49ie1Vo7Wm deployer@example.com
  aggs_for_vecs: true
  pg_repack: true

test:

development:

virtual:
  server_master_name: master
  server_cluster_name: cluster

staging:
  db_host: 127.0.0.1
  db_database: staging_web_tools
  db_username: staging_web_tools
  db_password: $SECRET +60k5KLqKuVpG4Iv6Lun4TFQbeyrki42N47JjYuBxEvmoNIIiDalV3xb--Uyu7eZU9Qxf3AL9B--yNZ5fovUhHbNaW1j00yygw==
  deployer_password: $SECRET gLF4Wc/KiQyRNYpQkjLsyCI6syOk7BIyIcOKa3gIDmdKmqPNgQr4X4Ow--VKhrY5TgnB3G3JaM--WRKYN1pfNDa6FebpPSALiQ==
  server_host:
  mail_to:
  mail_from:
  mail_address:
  mail_port:
  mail_domain:
  mail_username:
  # mail_password: $SECRET encrypted_secret
  owner_public_key:
  # owner_private_key: $SECRET encrypted_secret

production:
  db_host: 127.0.0.1
  db_database: production_web_tools
  db_username: production_web_tools
  db_password: $SECRET YtffoDUpU9coNeJCOcy1kNFgIws5YRIIq1yFWlsH3Pt7cfDZO1mOKNd5--baxA65Grq/SB62wj--ijzwJ90onfjdguFaJ6bbvw==
  deployer_password: $SECRET tTbqDusnf2eEAtE3TQU7qE+jblKdUh4Y5Lw6ViLnvTPaAjGYfUk9rwL/--FTjht++NLS5KsbIR--Npd45zsd0X8CHUe3Q3uoTQ==
  server_host:
  mail_to:
  mail_from:
  mail_address:
  mail_port:
  mail_domain:
  mail_username:
  # mail_password: $SECRET encrypted_secret
  owner_public_key:
  # owner_private_key: $SECRET encrypted_secret

cluster:
  server_cluster: true
