types:
  mail_to: emails
  backup_dir: pathname

shared:
  default_url_options: $METHOD
  server: $METHOD
  server_ssl: true
  mail_to: admin@email.example.com
  mail_from: noreply@email.example.com
  mail_address: localhost
  mail_port: 1025
  # mail_username: none
  # mail_password: none
  # mail_authentication: plain
  mail_enable_starttls_auto: true
  pg_stat_statements: true
  backup_split_size: 4GB
  backup_dir: /opt/storage/backup

test:
  server_host: localhost
  server_port: 3000
  server_ssl: false
  mail_domain: $ALIAS server
  backup_dir: ./tmp/test/backup

development:
  server_host: localhost
  server_port: 3000
  server_ssl: false
  mail_domain: $ALIAS server
  backup_dir: ./tmp/backup

virtual:
  server_host: virtual.test
  mail_domain: email.virtual.test
  backup_split_size: 4MB

staging:
  mail_authentication: login

production:
  mail_authentication: login
