import '@@/ext_pjax/concepts/device_concept'
import '@@/ext_pjax/concepts/i18n_concept'
import '@@/ext_pjax/concepts/routes_concept'
import '@@/ext_pjax/concepts/time_zone_concept'
import '@@/ext_pjax/concepts/toggle_concept'
import '@@/ext_pjax/concepts/ujs_concept'
