module ActiveRecord::Migration::WithPartition
  PARTITION = / PARTITION .+$/i
  TABLE = / TABLE (\w+) /i

  def create_partioned_table(name, key: :id)
    create_table_sql do
      case key
      when :id    then "CREATE TABLE #{name} (id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY) PARTITION BY RANGE (id)"
      when /_at$/ then "CREATE TABLE #{name} (#{key} TIMESTAMP(6) NOT NULL) PARTITION BY RANGE (#{key})"
      else             "CREATE TABLE #{name} (#{key} BIGINT NOT NULL) PARTITION BY RANGE (#{key})"
      end
    end
    if block_given?
      change_table name do |t|
        yield t
      end
    end
  end

  def create_table_sql
    sql = yield.strip_sql
    sql.sub! PARTITION, '' if Rails.env.test?
    partitioned = sql.match? PARTITION
    reversible do |change|
      change.up do
        exec_query sql
      end
      change.down do
        table = sql.match(TABLE).captures[0]
        exec_query "DROP TABLE IF EXISTS #{table}#{' CASCADE' if partitioned}"
      end
    end
  end
end
